version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: $MONGO_HOST
    hostname: $MONGO_HOST
    restart: unless-stopped
    ports:
      - $MONGO_HOST_PORT:$MONGO_CONTAINER_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
    volumes:
      - $MONGO_DATA_HOST_PATH:/data/db/
      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
      - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: $APP_NAME
    container_name: $APP_NAME
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - $SERVER_HOST_PORT:8080
    environment:
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - SPRING_APPLICATION_NAME=$APP_NAME
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - SPRING_DATA_MONGODB_HOST=$MONGO_HOST
      - SPRING_DATA_MONGODB_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_PORT=$MONGO_CONTAINER_PORT
      - SPRING_DATA_MONGODB_USERNAME=$MONGO_DB_USERNAME
      - SPRING_DATA_MONGODB_PASSWORD=$MONGO_DB_PASSWORD
      - SECURITY_JWT_TOKEN_SECRET_KEY=$JWT_SECRET_KEY
      - SECURITY_JWT_TOKEN_EXPIRE_LENGTH=$JWT_EXPIRE_LENGTH

