version: "3.8"
services:
  api_service:
    build: .
    restart: on-failure
    ports:
      - 25000:8080
    depends_on:
      - mongo
  mongo:
    image: "mongo:4.4.3"
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 26000:27017
